/* Generated By:JavaCC: Do not edit this line. SCDParserConstants.java */
package com.sun.xml.xsom.impl.scd;

public interface SCDParserConstants {

  int EOF = 0;
  int NCNAME = 6;
  int NUMBER = 7;
  int FACETNAME = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<NCNAME>",
    "<NUMBER>",
    "<FACETNAME>",
    "\":\"",
    "\"/\"",
    "\"//\"",
    "\"attribute::\"",
    "\"@\"",
    "\"element::\"",
    "\"substitutionGroup::\"",
    "\"type::\"",
    "\"~\"",
    "\"baseType::\"",
    "\"primitiveType::\"",
    "\"itemType::\"",
    "\"memberType::\"",
    "\"scope::\"",
    "\"attributeGroup::\"",
    "\"group::\"",
    "\"identityContraint::\"",
    "\"key::\"",
    "\"notation::\"",
    "\"model::sequence\"",
    "\"model::choice\"",
    "\"model::all\"",
    "\"model::*\"",
    "\"any::*\"",
    "\"anyAttribute::*\"",
    "\"facet::*\"",
    "\"facet::\"",
    "\"component::*\"",
    "\"*\"",
    "\"0\"",
  };

}
